### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by TristPW** [11sanach11/telegram-mailing-helper#1]
Hi,
What parameters does config.json accept? What are these parameters responsible for?
After update.sh the line appears http://host:port/info What exactly should be understood instead of host, port by default, if no parameters were entered in config. json?

**Comment by 11sanach11** [comment]
Pararmeters from config.json:server mapped in file telegram_mailing_help/web/config.py, this file contains default values, port by default is 23445

**Comment by TristPW** [comment]
Thanks!
